name: Build and Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ros: ["noetic", "humble", "jazzy"]
        cuda: ["11.4", "11.8", "12.0", "12.2", "12.4", "12.6", "12.8"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Free Up Disk Space
        run: |
          sudo apt-get clean
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /var/lib/apt/lists/*
          sudo rm -rf /var/lib/dpkg/info/*
          sudo rm -rf /usr/share/man/*
          sudo rm -rf /usr/share/doc/*
          docker system prune -af --volumes
          df -h

      - name: Run Tests
        run: python3 utils/tests.py

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Multi-Arch Docker Image (with cache)
        run: |
          DOCKER_BUILDKIT=1 \
          DOCKER_PUSH_IMAGES=true \
          python3 build.py --ros "${{ matrix.ros }}" --cuda "${{ matrix.cuda }}"
        env:
          BUILDX_CACHE_FROM: type=gha
          BUILDX_CACHE_TO: type=gha,mode=max

      - name: Clean Up Unused Docker Cache
        run: docker buildx prune -af

      - name: Logout from Docker Hub
        run: docker logout

