name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ros: ["noetic", "humble", "jazzy"]
        cuda: ["11.4", "11.8", "12.0", "12.2", "12.4", "12.6", "12.8"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker Layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ matrix.ros }}-${{ matrix.cuda }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=$(bash ./build_image.sh "${{ matrix.ros }}" "${{ matrix.cuda }}" | tail -n 1)
          if [ $? -ne 0 ]; then
            echo "Pushing image: $IMAGE_NAME"
            docker push $IMAGE_NAME
          fi

      - name: Clean Up Docker Resources
        run: docker system prune -af

      - name: Update Cache After Build
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Logout from Docker Hub
        run: docker logout
