name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - ros: "noetic"
            cuda: ["11.0", "11.4", "11.8", "12.0", "12.2", "12.4", "12.6", "12.8"]
          - ros: "humble"
            cuda: ["11.7", "11.8", "12.1", "12.2", "12.3", "12.4", "12.6", "12.8"]
          - ros: "jazzy"
            cuda: ["12.2", "12.3", "12.4", "12.6", "12.8"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Images
        run: |
          for CUDA_VERSION in "${{ join(matrix.cuda, ' ') }}"; do
            IMAGE_NAME=$(bash ./build_image.sh "${{ matrix.ros }}" "$CUDA_VERSION" | tail -n 1)
            if [ -n "$IMAGE_NAME" ]; then
              echo "Pushing image: $IMAGE_NAME"
              docker push $IMAGE_NAME
            else
              echo "Error: No image name returned from build script."
              exit 1
            fi
          done

      - name: Logout from Docker Hub
        run: docker logout
