name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ros: ["noetic", "humble", "jazzy"]
        cuda: ["11.4", "11.8", "12.0", "12.2", "12.4", "12.6", "12.8"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Free Up Disk Space
        run: |
          echo "Freeing up runner disk space..."
          sudo apt-get clean
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/share/dotnet
          docker system prune -af --volumes
          df -h

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container

      - name: Cache Docker Layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ matrix.ros }}-${{ matrix.cuda }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          DOCKER_BUILDKIT=1 \
          DOCKER_CACHE_FROM="/tmp/.buildx-cache" \
          DOCKER_CACHE_TO="/tmp/.buildx-cache-new" \
          IMAGE_NAME=$(bash ./build_image.sh "${{ matrix.ros }}" "${{ matrix.cuda }}" | tail -n 1)
          if [ $? -ne 0 ]; then
            echo "Pushing image: $IMAGE_NAME"
            docker push $IMAGE_NAME
          else
            exit 1
          fi

      - name: Clean Up Docker Resources
        run: docker system prune -af --volumes

      - name: Update Cache After Build
        run: |
          rm -rf /tmp/.buildx-cache
          if [ -d /tmp/.buildx-cache-new ]; then
            mv /tmp/.buildx-cache-new /tmp/.buildx-cache
          fi

      - name: Logout from Docker Hub
        run: docker logout
