name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ros: ["noetic", "humble", "jazzy"]
        cuda: ["11.4", "11.8", "12.0", "12.2", "12.4", "12.6", "12.8"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Free Up Disk Space
        run: |
          echo "Freeing up runner disk space..."
          sudo apt-get clean
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/share/dotnet
          docker system prune -af --volumes
          df -h

#      - name: Set up Python Environment
#        run: |
#          python3 -m venv .venv
#          source .venv/bin/activate
#          pip install -r requirements.txt

      - name: Run Tests
        run: python3 utils/tests.py
#        run: |
#          source .venv/bin/activate
#          python3 -m unittest discover -s utils -p "tests.py"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container

      - name: Cache Docker Layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ matrix.ros }}-${{ matrix.cuda }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-docker-${{ matrix.ros }}-${{ matrix.cuda }}
            ${{ runner.os }}-docker-

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          DOCKER_BUILDKIT=1 \
          PUSH_IMAGES=true \
          DOCKER_CACHE_FROM="/tmp/.buildx-cache" \
          DOCKER_CACHE_TO="/tmp/.buildx-cache-new" \
          python3 build.py --ros "${{ matrix.ros }}" --cuda "${{ matrix.cuda }}"

      - name: Clean Up Docker Resources
        run: |
          docker system prune -af --volumes
          df -h

      - name: Update Cache After Build
        run: |
          rm -rf /tmp/.buildx-cache
          if [ -d /tmp/.buildx-cache-new ]; then
            mv /tmp/.buildx-cache-new /tmp/.buildx-cache
          fi

      - name: Logout from Docker Hub
        run: docker logout
